language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt

env:
  - TRAVIS=true

script:
  - "coverage run --source=FantasyWeb,League manage.py test"

after_success:
  - "coveralls"
