# Generated by Django 2.1 on 2018-08-17 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('owner_limit', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='League_Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=25)),
                ('is_commish', models.BooleanField(default=False)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='League.League')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('team', models.CharField(max_length=3)),
                ('number', models.CharField(max_length=3)),
                ('position', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=5)),
                ('height', models.CharField(max_length=5)),
                ('weight', models.CharField(max_length=5)),
                ('dob', models.CharField(max_length=10)),
                ('experience', models.CharField(max_length=3)),
                ('college', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('name', 'dob', 'college')},
        ),
        migrations.AlterUniqueTogether(
            name='league_member',
            unique_together={('league', 'member'), ('league', 'team_name')},
        ),
    ]
